version: "3.6"
services:
  nats-server:
    restart: always
    image: "nats:latest"
    container_name: "nats-server"
    networks:
      - chat-network

  nginx:
    restart: always
    container_name: "nginx"
    build: "./nginx"
    ports:
      - "80:80"
    networks:
      - chat-network

#  backend:
#    container_name: "backend"
#    build: "."
#    networks:
#      - chat-network

networks:
  chat-network:
    driver: bridge
